import { useState, useEffect, useCallback } from 'react';
import { useToast } from '../../components/ui/Toast';

interface Project {
    id: string;
    title: string;
    description: string;
    objective: string;
    actions: string[];
    status: 'active' | 'completed' | 'on_hold' | 'cancelled';
    impact?: string;
    createdAt: string;
}

import { API_URL } from '../../config';

export const ProjectsView = ({ token }: { token: string }) => {
    const { addToast } = useToast();
    const [projects, setProjects] = useState<Project[]>([]);
    const [loading, setLoading] = useState(true);

    const fetchProjects = useCallback(async () => {
        if (!token) return;
        try {
            const res = await fetch(`${API_URL}/api/projects`, {
                headers: { Authorization: `Bearer ${token}` }
            });
            if (res.ok) {
                const data = await res.json();
                setProjects(data);
            }
        } catch (error) {
            addToast('Failed to load projects', 'error');
        } finally {
            setLoading(false);
        }
    }, [token, addToast]);

    useEffect(() => {
        fetchProjects();
    }, [fetchProjects]);

    const updateStatus = async (id: string, status: string) => {
        try {
            const res = await fetch(`${API_URL}/api/projects/${id}/status`, {
                method: 'PATCH',
                headers: {
                    'Content-Type': 'application/json',
                    Authorization: `Bearer ${token}`
                },
                body: JSON.stringify({ status })
            });
            if (res.ok) {
                fetchProjects();
                addToast('Status updated', 'success');
            }
        } catch (error) {
            addToast('Update failed', 'error');
        }
    };

    const deleteProject = async (id: string) => {
        if (!confirm('Archive this project?')) return;
        try {
            const res = await fetch(`${API_URL}/api/projects/${id}`, {
                method: 'DELETE',
                headers: { Authorization: `Bearer ${token}` }
            });
            if (res.ok) {
                setProjects(projects.filter(p => p.id !== id));
                addToast('Project archived', 'success');
            }
        } catch (error) {
            addToast('Delete failed', 'error');
        }
    };

    if (loading) return <div className="p-10 text-center">Loading Strategic Board...</div>;

    const activeProjects = projects.filter(p => p.status === 'active');
    const completedProjects = projects.filter(p => p.status === 'completed');

    return (
        <div className="flex-col gap-10 fade-in" style={{ padding: '32px', maxWidth: '1400px', margin: '0 auto', fontFamily: 'Dubai, sans-serif' }}>
            <div className="flex justify-between items-center">
                <div>
                    <h1 className="text-h1">Strategic Board</h1>
                    <p className="text-sec">Manage management-led initiatives generated by Nexus AI.</p>
                </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-10">
                {/* Active Projects */}
                <div className="flex-col gap-6">
                    <h3 className="text-h3 flex items-center gap-2">
                        <span style={{ width: '10px', height: '10px', borderRadius: '50%', background: 'var(--primary)' }}></span>
                        In Execution ({activeProjects.length})
                    </h3>
                    <div className="flex-col gap-4">
                        {activeProjects.map(project => (
                            <div key={project.id} className="card p-6 glass-card" style={{ borderLeft: '4px solid var(--primary)' }}>
                                <div className="flex justify-between items-start mb-4">
                                    <div className="flex-col gap-1">
                                        <span className="text-[10px] font-black uppercase tracking-widest text-primary">{project.objective.replace('_', ' ')}</span>
                                        <h4 className="font-bold text-xl">{project.title}</h4>
                                    </div>
                                    <div className="text-right">
                                        <span className="text-[10px] text-tertiary block font-black">IMPACT</span>
                                        <span className="text-success font-black text-lg">{project.impact}</span>
                                    </div>
                                </div>
                                <p className="text-sm text-sec mb-6 line-clamp-2">{project.description}</p>

                                <div className="flex-col gap-2 mb-6">
                                    <span className="text-[10px] font-black uppercase text-tertiary mb-1">Key Actions</span>
                                    {project.actions.slice(0, 2).map((a, i) => (
                                        <div key={i} className="flex gap-2 items-center text-xs p-2 rounded bg-bg-surface">
                                            <span style={{ color: 'var(--primary)', fontWeight: 900 }}>{i + 1}</span>
                                            <span>{a}</span>
                                        </div>
                                    ))}
                                    {project.actions.length > 2 && <span className="text-[10px] text-tertiary ml-2">+{project.actions.length - 2} more...</span>}
                                </div>

                                <div className="flex justify-between items-center pt-4 border-t border-subtle">
                                    <div className="flex gap-2">
                                        <button className="btn btn-ghost btn-sm" onClick={() => updateStatus(project.id, 'completed')}>Done</button>
                                        <button className="btn btn-ghost btn-sm" onClick={() => deleteProject(project.id)}>Archive</button>
                                    </div>
                                    <span className="text-[10px] text-tertiary">{new Date(project.createdAt).toLocaleDateString()}</span>
                                </div>
                            </div>
                        ))}
                        {activeProjects.length === 0 && <div className="card p-8 text-center text-sec opacity-50 dashed-border">No active projects. Use Nexus AI to generate new strategies.</div>}
                    </div>
                </div>

                {/* Completed */}
                <div className="flex-col gap-6">
                    <h3 className="text-h3 flex items-center gap-2 opacity-60">
                        <span style={{ width: '10px', height: '10px', borderRadius: '50%', background: 'var(--success)' }}></span>
                        Value Realized ({completedProjects.length})
                    </h3>
                    <div className="flex-col gap-4 opacity-70">
                        {completedProjects.map(project => (
                            <div key={project.id} className="card p-6" style={{ background: 'var(--bg-app)', borderLeft: '4px solid var(--success)' }}>
                                <div className="flex justify-between items-center">
                                    <div className="flex-col">
                                        <h4 className="font-bold">{project.title}</h4>
                                        <span className="text-xs text-sec">Realized {new Date(project.createdAt).toLocaleDateString()}</span>
                                    </div>
                                    <span className="text-success font-black">{project.impact}</span>
                                </div>
                            </div>
                        ))}
                    </div>
                </div>
            </div>

            <style>{`
                .glass-card { background: rgba(var(--bg-card-rgb), 0.5); backdrop-filter: blur(10px); }
                .line-clamp-2 { display: -webkit-box; -webkit-line-clamp: 2; -webkit-box-orient: vertical; overflow: hidden; }
                .dashed-border { border: 2px dashed var(--border-default); background: transparent; }
            `}</style>
        </div>
    );
};
