/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface KMeansResult {
  clusters: Array<Array<number>>
  labels: Array<number>
}
export declare function performKmeans(data: Array<number>, k: number, maxIterations: number): KMeansResult
