import { Request, Response } from 'express';
import { AiService } from '../services/aiService';

const aiService = new AiService();

export const handleNlqQuery = async (req: Request, res: Response) => {
    try {
        const { query, schema } = req.body;
        if (!query) {
            return res.status(400).json({ error: 'Query is required' });
        }

        const systemPrompt = `You are a data analyst AI specialized in translating natural language dataset queries into AlaSQL queries and providing insights.
Given the dataset schema, return a JSON object with the following structure:
{
    "sql": "string (a valid AlaSQL query that filters or aggregates the data)",
        "chartType": "string (e.g., 'bar', 'line', 'pie', 'table', 'number' - choose the most appropriate visualization type for the query result)",
            "chartTitle": "string (a concise title for the chart)",
                "interpretation": "string (a brief explanation of what the query result means or highlights)",
                    "followUpQuestions": ["string", "string", "string"](3 relevant follow - up questions a user might ask based on this query)
}

Dataset is available as "?".
Example 1: "Show me sales in Berlin last Q3"
Output:
{
    "sql": "SELECT * FROM ? WHERE City = 'Berlin' AND Date >= '2023-07-01' AND Date <= '2023-09-30'",
        "chartType": "table",
            "chartTitle": "Sales in Berlin (Q3 2023)",
                "interpretation": "This query retrieves all sales records for Berlin during the third quarter of 2023, showing detailed transactions.",
                    "followUpQuestions": [
                        "What were the total sales in Berlin during Q3?",
                        "Which products sold best in Berlin during Q3?",
                        "How do Berlin's Q3 sales compare to other cities?"
                    ]
}
Example 2: "Total revenue by country"
Output:
{
    "sql": "SELECT Country, SUM(Revenue) as TotalRevenue FROM ? GROUP BY Country",
        "chartType": "bar",
            "chartTitle": "Total Revenue by Country",
                "interpretation": "This query aggregates the total revenue generated by each country, providing a high-level overview of geographical performance.",
                    "followUpQuestions": [
                        "Which country generated the highest revenue?",
                        "What is the average revenue per country?",
                        "Can we see the revenue trend for the top 3 countries?"
                    ]
}
Example 3: "Top 5 products by sales"
Output:
{
    "sql": "SELECT Product, SUM(Sales) as TotalSales FROM ? GROUP BY Product ORDER BY TotalSales DESC LIMIT 5",
        "chartType": "bar",
            "chartTitle": "Top 5 Products by Sales",
                "interpretation": "This query identifies the five products with the highest total sales, indicating key revenue drivers.",
                    "followUpQuestions": [
                        "What is the total sales value for these top 5 products?",
                        "Are these top products consistent across different regions?",
                        "What was the sales trend for the top product over time?"
                    ]
}

Schema(Columns and types):
${JSON.stringify(schema)}

Return ONLY the raw JSON object without markdown blocks or explanations.Do not wrap in \`\`\`json ... \`\`\`.
`;

        const responseText = await aiService.generateText(query, systemPrompt);

        // Clean and parse the JSON response
        const cleanJson = responseText.replace(/```json\n?/g, '').replace(/```\n?/g, '').trim();
        let parsedResponse;
        try {
            parsedResponse = JSON.parse(cleanJson);
        } catch (jsonError) {
            console.error('NLQ JSON Parsing Error:', jsonError);
            console.error('Malformed JSON received:', cleanJson);
            return res.status(500).json({ error: 'Failed to parse AI response as JSON', rawResponse: cleanJson });
        }

        // Basic validation for the expected fields
        if (!parsedResponse.sql || !parsedResponse.chartType || !parsedResponse.chartTitle || !parsedResponse.interpretation || !Array.isArray(parsedResponse.followUpQuestions)) {
            console.error('NLQ AI response missing expected fields:', parsedResponse);
            return res.status(500).json({ error: 'AI response missing required fields', response: parsedResponse });
        }

        res.json(parsedResponse);
    } catch (error: any) {
        console.error('NLQ Error:', error);
        res.status(500).json({ error: 'Failed to process NLQ' });
    }
};

export const generateSynthesis = async (req: Request, res: Response) => {
    try {
        const { datasetName, rows, columns, anomalies, trends, metrics } = req.body;

        const systemPrompt = `You are an expert Chief Executive Data Scientist for a top-tier management consultancy.
You are tasked with generating a high-level strategic reasoning synthesis for a dataset analysis.
You MUST write EXACTLY 3 paragraphs:
Paragraph 1: Executive Summary - What dataset we are looking at, its size, global context, and the high-level operational picture.
Paragraph 2: The Meaning Behind the Numbers - Dive into what the identified anomalies, trends, or metrics actually indicate for the organization's systemic health or friction points.
Paragraph 3: Strategic Prescriptions - Direct, actionable recommendations that leverage the findings to improve operations, mitigate risks, or capitalize on growth vectors.

You must output in a structured JSON format with this exact schema:
{
  "executiveSummary": "string (all 3 paragraphs combined or separated by \\n\\n)",
  "strategicAdvice": ["string", "string", "string", "string"],
  "priorityMatrix": [
    { "task": "string", "impact": "High|Medium|Low", "effort": "High|Medium|Low" }
  ]
}

Return ONLY valid JSON.
`;

        const userPrompt = `Dataset Name: ${datasetName}
Rows: ${rows}
Columns: ${columns}
Metrics: ${JSON.stringify(metrics)}
Anomalies: ${JSON.stringify(anomalies)}
Trends: ${JSON.stringify(trends)}`;

        const responseText = await aiService.generateText(userPrompt, systemPrompt);
        const cleanJson = responseText.replace(/```json/g, '').replace(/```/g, '').trim();
        let parsed;
        try {
            parsed = JSON.parse(cleanJson);
        } catch (jsonError) {
            console.error('Synthesis JSON Parsing Error:', jsonError);
            console.error('Malformed JSON received:', cleanJson);
            return res.status(500).json({ error: 'Failed to parse AI synthesis response as JSON', rawResponse: cleanJson });
        }

        res.json(parsed);
    } catch (error: any) {
        console.error('Synthesis Error:', error);
        res.status(500).json({ error: 'Failed to generate synthesis' });
    }
};
