import React, { createContext, useContext, useState, type ReactNode } from 'react';

type Language = 'en' | 'de';

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
    en: {
        // ─── Landing ───
        'landing.new': 'New: AI Actions & Forecasting',
        'landing.hero.title1': 'Turn raw data into',
        'landing.hero.title2': 'strategic intelligence.',
        'landing.hero.subtitle': 'From exploratory analysis to predictive forecasting — one platform for your entire data lifecycle.',
        'landing.cta.start': 'Start Analyzing',
        'landing.cta.startFree': 'Start Analyzing — Free',
        'landing.cta.explore': 'Explore Forecasting',
        'landing.footer.copy': '© 2026 Nalyse. All rights reserved.',
        'landing.footer.privacy': 'Privacy',
        'landing.footer.security': 'Security',
        'landing.footer.contact': 'Contact',
        'landing.final.title1': 'Ready to see the',
        'landing.final.title2': 'difference?',
        'landing.final.note': 'No credit card required.',
        // Landing: Chapters
        'landing.ch1.tag': 'ANALYTICS STUDIO',
        'landing.ch1.title': 'See what others miss.',
        'landing.ch1.desc': 'Six analysis engines work together — real-time SQL, interactive visualizations, statistical correlation, anomaly detection, and financial risk modeling — all on your live data.',
        'landing.ch2.tag': 'PREDICTIVE INTELLIGENCE',
        'landing.ch2.title': 'Know what happens next.',
        'landing.ch2.desc': 'Machine learning forecasting, geospatial mapping, and AutoML optimization — purpose-built for teams who need to see around corners.',
        'landing.ch3.tag': 'BUSINESS INTELLIGENCE',
        'landing.ch3.title1': 'From data to',
        'landing.ch3.title2': 'boardroom.',
        'landing.ch3.desc': 'Executive dashboards, strategic boards, and a visual architect that aligns your entire organization around a single source of truth.',
        // Landing: Process
        'landing.process.tag': 'HOW IT WORKS',
        'landing.process.title': 'Five steps. Zero friction.',
        'landing.process.desc': 'From raw file to strategic insight — every step is automated, auditable, and fast.',
        // Landing: Pipeline
        'landing.pipeline.connect': 'Connect',
        'landing.pipeline.process': 'Process',
        'landing.pipeline.analyze': 'Analyze',
        'landing.pipeline.predict': 'Predict',
        'landing.pipeline.execute': 'Execute',
        // Landing: Trust
        'landing.trust.tools': 'Analysis Tools',
        'landing.trust.processing': 'Data Processing',
        'landing.trust.realtime': 'Real-Time',
        'landing.trust.rbac': 'RBAC & Encryption',
        'landing.trust.enterprise': 'Enterprise',
        'landing.trust.forecasting': 'Forecasting & AutoML',
        'landing.trust.mlPowered': 'ML-Powered',
        // Landing: Deep Dive
        'landing.deep.tag': 'DEEP DIVE',
        'landing.deep.title': 'Smart Lens in action.',
        'landing.deep.step1.title': 'Upload your data',
        'landing.deep.step1.desc': 'Drag and drop CSV, Excel, or JSON files. Schema is auto-detected in milliseconds.',
        'landing.deep.step2.title': 'AI finds patterns',
        'landing.deep.step2.desc': 'Smart Lens scans every column, detects anomalies, correlations, and statistical patterns automatically.',
        'landing.deep.step3.title': 'Get actionable insights',
        'landing.deep.step3.desc': 'Receive clear, prioritized recommendations with confidence scores — ready for strategic decisions.',
        // Landing: Forecast Visual
        'landing.forecast.active': 'Forecast Active',
        // Landing: Dashboard Visual labels
        'landing.dashVis.revenue': 'Revenue Trend',
        'landing.dashVis.conversion': 'Conversion',
        'landing.dashVis.status': 'Status',
        'landing.dashVis.allActive': 'All Systems Active',
        'landing.dashVis.forecastAccuracy': 'Forecast Accuracy',

        // ─── Navigation ───
        'nav.home': 'Home',
        'nav.workspace': 'Analysis',
        'nav.bi': 'BI Dashboards',
        'nav.correlation': 'Correlation',
        'nav.settings': 'Settings',
        'nav.simulation': 'Simulation Engine',
        'nav.lens': 'Smart Lens',
        'nav.diff': 'Version Diff',
        'nav.anomaly': 'Anomaly Detection',
        'nav.financial': 'Financial Risk',
        'nav.forecast': 'Forecasting Engine',
        'nav.spatial': 'Geospatial Intelligence',
        'nav.automl': 'AutoML Intelligence',
        'nav.developer': 'Developer API',
        'nav.webhooks': 'Webhooks & API',
        'nav.embed': 'Embed SDK',
        'nav.canvas': 'Dashboard Canvas',
        'nav.projects': 'Strategic Board',
        'nav.democracy': 'Self-Service Studio',
        'nav.automation': 'Automated Reports',
        'nav.collaboration': 'Collaboration',
        'nav.sharedWorkspaces': 'Shared Workspaces',
        'nav.privateChat': 'Personal Chat',
        'nav.sources': 'Data Connectors',
        'nav.migration': 'Data Migration',
        'nav.organization': 'Organization & RBAC',
        'nav.docs': 'Work Instructions',

        // ─── Header ───
        'header.welcome': 'Welcome back',
        'header.goodMorning': 'Good morning',
        'header.goodAfternoon': 'Good afternoon',
        'header.goodEvening': 'Good evening',
        'header.profile': 'Profile',
        'header.logout': 'Logout',
        'header.signedInAs': 'Signed in as',
        'header.settings': 'Setting',

        // ─── Dashboard ───
        'dashboard.upload.title': 'Upload Data',
        'dashboard.upload.subtitle': 'Drag and drop your CSV or Excel files here',
        'dashboard.recent': 'Recent Files',
        'dashboard.actions': 'Actions',
        'dashboard.empty': 'No files uploaded yet.',
        'dashboard.delete': 'Delete',
        'dashboard.analyze': 'Analyze',
        'dashboard.searchDatasets': 'Search datasets...',
        'dashboard.upgradeNow': 'Upgrade Now',
        'dashboard.openAnalysis': 'Open Analysis',
        'dashboard.launchNeural': 'Launch Neural Analysis',

        // ─── Auth: Login ───
        'auth.login.secureAccess': 'Secure Access',
        'auth.login.welcomeBack': 'Welcome back',
        'auth.login.subtitle': 'Sign in to your account to continue',
        'auth.login.emailLabel': 'Email Address',
        'auth.login.passwordLabel': 'Password',
        'auth.login.emailPlaceholder': 'you@company.com',
        'auth.login.passwordPlaceholder': 'Enter your password',
        'auth.login.signIn': 'Sign In',
        'auth.login.or': 'or',
        'auth.login.createAccount': 'Create a new account',
        'auth.login.securityNote': 'Protected by enterprise-grade security',
        'auth.login.heroDesc': 'Enterprise data intelligence platform.',
        'auth.login.heroSubDesc': 'Transform raw data into actionable insights.',
        'auth.login.badgeSoc': 'SOC 2 Compliant',
        'auth.login.badgeE2e': 'E2E Encrypted',
        'auth.login.badgeAi': 'AI-Powered',

        // ─── Auth: Register ───
        'auth.register.getStarted': 'Get Started',
        'auth.register.heroDesc': 'Join thousands of data teams using Nalyse to power their analytics.',
        'auth.register.badgeSetup': 'Instant Setup',
        'auth.register.badgeFree': 'Free Tier',
        'auth.register.badgeNoCard': 'No Credit Card',
        'auth.register.stepOf': 'Step {current} of {total}',
        // Step 0
        'auth.register.createAccount': 'Create Account',
        'auth.register.yourInfo': 'Your information',
        'auth.register.startBasics': "Let's start with the basics",
        'auth.register.emailLabel': 'Email Address',
        'auth.register.firstNameLabel': 'First Name',
        'auth.register.lastNameLabel': 'Last Name',
        // Step 1
        'auth.register.orgTag': 'Organization',
        'auth.register.yourWorkspace': 'Your workspace',
        'auth.register.workspaceDesc': "This will be your team's shared environment",
        'auth.register.orgNameLabel': 'Organization Name',
        // Step 2
        'auth.register.securityTag': 'Security',
        'auth.register.secureAccount': 'Secure your account',
        'auth.register.secureDesc': 'Choose a strong password to protect your data',
        'auth.register.passwordLabel': 'Password',
        'auth.register.confirmPasswordLabel': 'Confirm Password',
        'auth.register.passwordPlaceholder': 'Min 8 characters',
        'auth.register.confirmPlaceholder': 'Repeat your password',
        'auth.register.passwordsMatch': 'Passwords match',
        'auth.register.createBtn': 'Create Account',
        'auth.register.continueBtn': 'Continue',
        'auth.register.alreadyHaveAccount': 'Already have an account?',
        'auth.register.signIn': 'Sign in',
        'auth.register.provisioning': 'Provisioning...',
        'auth.register.accountCreated': 'Account Created',
        'auth.register.settingUp': 'Setting up your workspace',
        'auth.register.welcomeAboard': 'Welcome aboard! Redirecting...',
        // Validation messages
        'auth.register.validEmail': 'Please enter a valid email.',
        'auth.register.fullNameRequired': 'Full name is required.',
        'auth.register.orgRequired': 'Organization name required.',
        'auth.register.passwordMin': 'Password must be at least 8 characters.',
        'auth.register.passwordMismatch': 'Passwords do not match.',
        'auth.register.registerFailed': 'Registration failed. Please try again.',

        // ─── Settings ───
        'settings.title': 'Settings',
        'settings.back': 'Back',
        'settings.signOut': 'Sign Out',
        'settings.tabs.account': 'Account',
        'settings.tabs.billing': 'Billing & Plans',
        'settings.tabs.api': 'API Keys',
        'settings.tabs.notifications': 'Notifications',
        'settings.profile.picture': 'Profile Picture',
        'settings.profile.uploadPicture': 'Upload New Picture',
        'settings.profile.pictureHint': 'JPG, GIF or PNG. Max 800KB',
        'settings.profile.personalInfo': 'Personal Information',
        'settings.profile.firstName': 'First Name',
        'settings.profile.lastName': 'Last Name',
        'settings.profile.email': 'Email Address',
        'settings.profile.organization': 'Organization',
        'settings.profile.personalAccount': 'Personal Account',
        'settings.profile.bio': 'Bio',
        'settings.profile.bioPlaceholder': 'Tell us about yourself...',
        'settings.profile.saving': 'Saving...',
        'settings.profile.saveChanges': 'Save Changes',
        'settings.profile.updatedSuccess': 'Profile updated successfully',
        'settings.profile.saveFailed': 'Failed to save changes',
        'settings.profile.pictureUpdated': 'Profile picture updated',
        'settings.profile.pictureUploadFailed': 'Failed to upload picture',
        'settings.appearance.title': 'Appearance',
        'settings.appearance.desc': 'Customize how Nalyse looks',
        'settings.appearance.light': 'Light',
        'settings.appearance.lightDesc': 'Clean & crisp',
        'settings.appearance.dark': 'Dark',
        'settings.appearance.darkDesc': 'Sleek & focused',
        'settings.appearance.custom': 'Custom',
        'settings.appearance.customDesc': 'Your own palette',
        'settings.appearance.system': 'System',
        'settings.appearance.systemDesc': 'Match your OS',
        // API
        'settings.api.secretKeys': 'Secret Keys',
        'settings.api.manageAuth': 'Manage API authentication',
        'settings.api.createNew': '+ Create New Key',
        'settings.api.noKeys': 'No API keys found. Create one to get started.',
        'settings.api.copy': 'Copy',
        'settings.api.revoke': 'Revoke',
        'settings.api.copied': 'Copied to clipboard',
        'settings.api.created': 'API Key created',
        'settings.api.createFailed': 'Failed to create key',
        'settings.api.revoked': 'API Key revoked',
        'settings.api.revokeFailed': 'Failed to revoke key',
        'settings.api.feature': 'API Access',
        'settings.api.featureDesc': 'Integrate Nalyse with your own applications and automate your data workflows with our robust API.',
        // Notifications
        'settings.notifications.title': 'Notification Preferences',
        'settings.notifications.desc': 'Configure how and when Nalyse alerts you across different platform modules.',
        'settings.notifications.collab.title': 'Collaboration & Messages',
        'settings.notifications.collab.desc': 'Stay updated on direct communication and teamwork.',
        'settings.notifications.collab.dm': 'Direct Messages',
        'settings.notifications.collab.dmDesc': 'Get notified when someone sends you a private message.',
        'settings.notifications.collab.mentions': 'Mentions',
        'settings.notifications.collab.mentionsDesc': 'Get notified when you are @mentioned in a workspace or comment.',
        'settings.notifications.collab.threadReplies': 'Thread Replies',
        'settings.notifications.collab.threadRepliesDesc': 'Get notified when someone replies to a thread you follow.',
        'settings.notifications.analysis.title': 'Analysis & Intelligence',
        'settings.notifications.analysis.desc': 'Alerts from the Neural Bridge and Decision Engine.',
        'settings.notifications.analysis.complete': 'Analysis Complete',
        'settings.notifications.analysis.completeDesc': 'Get notified when large data analysis jobs finish running.',
        'settings.notifications.analysis.automl': 'AutoML Readiness',
        'settings.notifications.analysis.automlDesc': 'Get notified when an AutoML model finishes training or deployment.',
        'settings.notifications.analysis.anomaly': 'Anomaly Alerts',
        'settings.notifications.analysis.anomalyDesc': 'Critical alerts when the Anomaly Detection engine flags unexpected deviations.',
        'settings.notifications.analysis.scheduled': 'Scheduled Reports',
        'settings.notifications.analysis.scheduledDesc': 'Get notified when your automated PDF/HTML reports are generated.',
        'settings.notifications.data.title': 'Data & Infrastructure',
        'settings.notifications.data.desc': 'Monitor your data pipelines and integrations.',
        'settings.notifications.data.syncFailure': 'Sync Failures',
        'settings.notifications.data.syncFailureDesc': 'Immediate alerts when a data connector fails to synchronize.',
        'settings.notifications.data.schemaChange': 'Schema Changes',
        'settings.notifications.data.schemaChangeDesc': 'Get notified when upstream source schemas change or break.',
        'settings.notifications.data.pipelineSuccess': 'Pipeline Success',
        'settings.notifications.data.pipelineSuccessDesc': 'Daily summary of successfully executed data pipelines.',
        'settings.notifications.security.title': 'Security & Account',
        'settings.notifications.security.desc': 'Protect your account and stay informed.',
        'settings.notifications.security.newLogins': 'New Logins',
        'settings.notifications.security.newLoginsDesc': 'Alerts for logins from new IP addresses or unrecognized devices.',
        'settings.notifications.security.roleChanges': 'Role & Access Changes',
        'settings.notifications.security.roleChangesDesc': 'Get notified when your permissions or RBAC roles are updated.',
        'settings.notifications.security.alerts': 'Security Alerts',
        'settings.notifications.security.alertsDesc': 'Important notifications about platform security events.',
        'settings.notifications.security.updates': 'Product Updates',
        'settings.notifications.security.updatesDesc': 'News about new Nalyse features, improvements, and maintenance.',

        // ─── BI Selection ───
        'bi.select.title': 'BI Intelligence Dashboards',
        'bi.select.subtitle': 'Select an analytical vector to instantiate your AI-powered visualization canvas.',
        'bi.sales.title': 'Sales & Revenue',
        'bi.sales.desc': 'Analyze financial performance, pipeline velocity, and regional sales distribution.',
        'bi.retention.title': 'Customer Retention',
        'bi.retention.desc': 'Track churn rates, cohort survival, and user engagement over time.',
        'bi.supply.title': 'Supply Chain',
        'bi.supply.desc': 'Monitor inventory levels, supplier performance, and reorder alerts.',
        'bi.marketing.title': 'Marketing ROI',
        'bi.marketing.desc': 'Evaluate campaign spend, conversion funnels, and cost per acquisition.',
        'bi.product.title': 'Product Analytics',
        'bi.product.desc': 'Understand feature usage, session duration, and user pathways.',
        'bi.executive.title': 'Executive Summary',
        'bi.executive.desc': 'High-level macroscopic view of business health, P&L, and strategic targets.',
        'bi.selectFile': 'Select existing dataset',
        'bi.chooseFile': 'Choose a file...',
        'bi.launchDashboard': 'Launch Dashboard',
        'bi.uploadNew': 'Upload new dataset',
        'bi.expectedColumns': 'Expected columns:',
        'bi.noFilesYet': 'No files uploaded yet',
    },
    de: {
        // ─── Landing ───
        'landing.new': 'Neu: KI-Aktionen & Prognosen',
        'landing.hero.title1': 'Rohdaten in',
        'landing.hero.title2': 'strategische Intelligenz verwandeln.',
        'landing.hero.subtitle': 'Von explorativer Analyse bis prädiktiver Prognose — eine Plattform für Ihren gesamten Datenlebenszyklus.',
        'landing.cta.start': 'Analyse starten',
        'landing.cta.startFree': 'Kostenlos starten — Gratis',
        'landing.cta.explore': 'Prognosen entdecken',
        'landing.footer.copy': '© 2026 Nalyse. Alle Rechte vorbehalten.',
        'landing.footer.privacy': 'Datenschutz',
        'landing.footer.security': 'Sicherheit',
        'landing.footer.contact': 'Kontakt',
        'landing.final.title1': 'Bereit, den',
        'landing.final.title2': 'Unterschied zu sehen?',
        'landing.final.note': 'Keine Kreditkarte erforderlich.',
        // Landing: Chapters
        'landing.ch1.tag': 'ANALYSE-STUDIO',
        'landing.ch1.title': 'Sehen, was andere übersehen.',
        'landing.ch1.desc': 'Sechs Analyse-Engines arbeiten zusammen — Echtzeit-SQL, interaktive Visualisierungen, statistische Korrelation, Anomalie-Erkennung und Finanzrisikomodellierung — alles auf Ihren Live-Daten.',
        'landing.ch2.tag': 'PRÄDIKTIVE INTELLIGENZ',
        'landing.ch2.title': 'Wissen, was als Nächstes kommt.',
        'landing.ch2.desc': 'Machine-Learning-Prognosen, Geospatial-Mapping und AutoML-Optimierung — maßgeschneidert für Teams, die vorausschauend handeln müssen.',
        'landing.ch3.tag': 'BUSINESS INTELLIGENCE',
        'landing.ch3.title1': 'Von Daten zum',
        'landing.ch3.title2': 'Vorstandstisch.',
        'landing.ch3.desc': 'Executive-Dashboards, strategische Boards und ein visueller Architekt, der Ihre gesamte Organisation auf eine einzige Quelle der Wahrheit ausrichtet.',
        // Landing: Process
        'landing.process.tag': 'SO FUNKTIONIERT ES',
        'landing.process.title': 'Fünf Schritte. Null Aufwand.',
        'landing.process.desc': 'Von der Rohdatei zur strategischen Erkenntnis — jeder Schritt ist automatisiert, nachvollziehbar und schnell.',
        // Landing: Pipeline
        'landing.pipeline.connect': 'Verbinden',
        'landing.pipeline.process': 'Verarbeiten',
        'landing.pipeline.analyze': 'Analysieren',
        'landing.pipeline.predict': 'Vorhersagen',
        'landing.pipeline.execute': 'Ausführen',
        // Landing: Trust
        'landing.trust.tools': 'Analyse-Tools',
        'landing.trust.processing': 'Datenverarbeitung',
        'landing.trust.realtime': 'Echtzeit',
        'landing.trust.rbac': 'RBAC & Verschlüsselung',
        'landing.trust.enterprise': 'Enterprise',
        'landing.trust.forecasting': 'Prognose & AutoML',
        'landing.trust.mlPowered': 'ML-gestützt',
        // Landing: Deep Dive
        'landing.deep.tag': 'TIEFER EINBLICK',
        'landing.deep.title': 'Smart Lens in Aktion.',
        'landing.deep.step1.title': 'Laden Sie Ihre Daten hoch',
        'landing.deep.step1.desc': 'Ziehen Sie CSV-, Excel- oder JSON-Dateien per Drag & Drop. Das Schema wird in Millisekunden automatisch erkannt.',
        'landing.deep.step2.title': 'KI findet Muster',
        'landing.deep.step2.desc': 'Smart Lens scannt jede Spalte, erkennt Anomalien, Korrelationen und statistische Muster automatisch.',
        'landing.deep.step3.title': 'Handlungsfähige Erkenntnisse erhalten',
        'landing.deep.step3.desc': 'Erhalten Sie klare, priorisierte Empfehlungen mit Konfidenzwerten — bereit für strategische Entscheidungen.',
        // Landing: Forecast Visual
        'landing.forecast.active': 'Prognose aktiv',
        // Landing: Dashboard Visual labels
        'landing.dashVis.revenue': 'Umsatzentwicklung',
        'landing.dashVis.conversion': 'Konversion',
        'landing.dashVis.status': 'Status',
        'landing.dashVis.allActive': 'Alle Systeme aktiv',
        'landing.dashVis.forecastAccuracy': 'Prognosegenauigkeit',

        // ─── Navigation ───
        'nav.home': 'Startseite',
        'nav.workspace': 'Analyse',
        'nav.bi': 'BI Dashboards',
        'nav.correlation': 'Korrelation',
        'nav.settings': 'Einstellungen',
        'nav.simulation': 'Simulations-Engine',
        'nav.lens': 'Smart Lens',
        'nav.diff': 'Versions-Vergleich',
        'nav.anomaly': 'Anomalie-Erkennung',
        'nav.financial': 'Finanzrisiko',
        'nav.forecast': 'Prognose-Engine',
        'nav.spatial': 'Geospatiale Intelligenz',
        'nav.automl': 'AutoML-Intelligenz',
        'nav.developer': 'Entwickler-API',
        'nav.webhooks': 'Webhooks & API',
        'nav.embed': 'Embed SDK',
        'nav.canvas': 'Dashboard-Canvas',
        'nav.projects': 'Strategisches Board',
        'nav.democracy': 'Self-Service Studio',
        'nav.automation': 'Automatisierte Berichte',
        'nav.collaboration': 'Zusammenarbeit',
        'nav.sharedWorkspaces': 'Geteilte Arbeitsbereiche',
        'nav.privateChat': 'Persönlicher Chat',
        'nav.sources': 'Datenquellen',
        'nav.migration': 'Datenmigration',
        'nav.organization': 'Organisation & RBAC',
        'nav.docs': 'Arbeitsanweisungen',

        // ─── Header ───
        'header.welcome': 'Willkommen zurück',
        'header.goodMorning': 'Guten Morgen',
        'header.goodAfternoon': 'Guten Tag',
        'header.goodEvening': 'Guten Abend',
        'header.profile': 'Profil',
        'header.logout': 'Abmelden',
        'header.signedInAs': 'Angemeldet als',
        'header.settings': 'Einstellung',

        // ─── Dashboard ───
        'dashboard.upload.title': 'Daten hochladen',
        'dashboard.upload.subtitle': 'Ziehen Sie Ihre CSV- oder Excel-Dateien hierher',
        'dashboard.recent': 'Kürzliche Dateien',
        'dashboard.actions': 'Aktionen',
        'dashboard.empty': 'Noch keine Dateien hochgeladen.',
        'dashboard.delete': 'Löschen',
        'dashboard.analyze': 'Analysieren',
        'dashboard.searchDatasets': 'Datensätze suchen...',
        'dashboard.upgradeNow': 'Jetzt upgraden',
        'dashboard.openAnalysis': 'Analyse öffnen',
        'dashboard.launchNeural': 'Neuronale Analyse starten',

        // ─── Auth: Login ───
        'auth.login.secureAccess': 'Sicherer Zugang',
        'auth.login.welcomeBack': 'Willkommen zurück',
        'auth.login.subtitle': 'Melden Sie sich an, um fortzufahren',
        'auth.login.emailLabel': 'E-Mail-Adresse',
        'auth.login.passwordLabel': 'Passwort',
        'auth.login.emailPlaceholder': 'sie@unternehmen.de',
        'auth.login.passwordPlaceholder': 'Passwort eingeben',
        'auth.login.signIn': 'Anmelden',
        'auth.login.or': 'oder',
        'auth.login.createAccount': 'Neues Konto erstellen',
        'auth.login.securityNote': 'Geschützt durch Sicherheit auf Unternehmensniveau',
        'auth.login.heroDesc': 'Enterprise-Datenintelligenz-Plattform.',
        'auth.login.heroSubDesc': 'Verwandeln Sie Rohdaten in umsetzbare Erkenntnisse.',
        'auth.login.badgeSoc': 'SOC 2 konform',
        'auth.login.badgeE2e': 'E2E-verschlüsselt',
        'auth.login.badgeAi': 'KI-gestützt',

        // ─── Auth: Register ───
        'auth.register.getStarted': 'Loslegen',
        'auth.register.heroDesc': 'Schließen Sie sich tausenden Datenteams an, die Nalyse für ihre Analysen nutzen.',
        'auth.register.badgeSetup': 'Sofortige Einrichtung',
        'auth.register.badgeFree': 'Kostenlos',
        'auth.register.badgeNoCard': 'Keine Kreditkarte',
        'auth.register.stepOf': 'Schritt {current} von {total}',
        // Step 0
        'auth.register.createAccount': 'Konto erstellen',
        'auth.register.yourInfo': 'Ihre Informationen',
        'auth.register.startBasics': 'Beginnen wir mit den Grundlagen',
        'auth.register.emailLabel': 'E-Mail-Adresse',
        'auth.register.firstNameLabel': 'Vorname',
        'auth.register.lastNameLabel': 'Nachname',
        // Step 1
        'auth.register.orgTag': 'Organisation',
        'auth.register.yourWorkspace': 'Ihr Arbeitsbereich',
        'auth.register.workspaceDesc': 'Dies wird die gemeinsame Umgebung Ihres Teams',
        'auth.register.orgNameLabel': 'Organisationsname',
        // Step 2
        'auth.register.securityTag': 'Sicherheit',
        'auth.register.secureAccount': 'Konto absichern',
        'auth.register.secureDesc': 'Wählen Sie ein sicheres Passwort zum Schutz Ihrer Daten',
        'auth.register.passwordLabel': 'Passwort',
        'auth.register.confirmPasswordLabel': 'Passwort bestätigen',
        'auth.register.passwordPlaceholder': 'Mindestens 8 Zeichen',
        'auth.register.confirmPlaceholder': 'Passwort wiederholen',
        'auth.register.passwordsMatch': 'Passwörter stimmen überein',
        'auth.register.createBtn': 'Konto erstellen',
        'auth.register.continueBtn': 'Weiter',
        'auth.register.alreadyHaveAccount': 'Sie haben bereits ein Konto?',
        'auth.register.signIn': 'Anmelden',
        'auth.register.provisioning': 'Wird bereitgestellt...',
        'auth.register.accountCreated': 'Konto erstellt',
        'auth.register.settingUp': 'Arbeitsbereich wird eingerichtet',
        'auth.register.welcomeAboard': 'Willkommen an Bord! Weiterleitung...',
        // Validation messages
        'auth.register.validEmail': 'Bitte geben Sie eine gültige E-Mail-Adresse ein.',
        'auth.register.fullNameRequired': 'Vollständiger Name ist erforderlich.',
        'auth.register.orgRequired': 'Organisationsname erforderlich.',
        'auth.register.passwordMin': 'Passwort muss mindestens 8 Zeichen lang sein.',
        'auth.register.passwordMismatch': 'Passwörter stimmen nicht überein.',
        'auth.register.registerFailed': 'Registrierung fehlgeschlagen. Bitte versuchen Sie es erneut.',

        // ─── Settings ───
        'settings.title': 'Einstellungen',
        'settings.back': 'Zurück',
        'settings.signOut': 'Abmelden',
        'settings.tabs.account': 'Konto',
        'settings.tabs.billing': 'Abrechnung & Pläne',
        'settings.tabs.api': 'API-Schlüssel',
        'settings.tabs.notifications': 'Benachrichtigungen',
        'settings.profile.picture': 'Profilbild',
        'settings.profile.uploadPicture': 'Neues Bild hochladen',
        'settings.profile.pictureHint': 'JPG, GIF oder PNG. Max. 800 KB',
        'settings.profile.personalInfo': 'Persönliche Informationen',
        'settings.profile.firstName': 'Vorname',
        'settings.profile.lastName': 'Nachname',
        'settings.profile.email': 'E-Mail-Adresse',
        'settings.profile.organization': 'Organisation',
        'settings.profile.personalAccount': 'Persönliches Konto',
        'settings.profile.bio': 'Biografie',
        'settings.profile.bioPlaceholder': 'Erzählen Sie uns etwas über sich...',
        'settings.profile.saving': 'Wird gespeichert...',
        'settings.profile.saveChanges': 'Änderungen speichern',
        'settings.profile.updatedSuccess': 'Profil erfolgreich aktualisiert',
        'settings.profile.saveFailed': 'Änderungen konnten nicht gespeichert werden',
        'settings.profile.pictureUpdated': 'Profilbild aktualisiert',
        'settings.profile.pictureUploadFailed': 'Bild konnte nicht hochgeladen werden',
        'settings.appearance.title': 'Erscheinungsbild',
        'settings.appearance.desc': 'Passen Sie das Aussehen von Nalyse an',
        'settings.appearance.light': 'Hell',
        'settings.appearance.lightDesc': 'Klar & frisch',
        'settings.appearance.dark': 'Dunkel',
        'settings.appearance.darkDesc': 'Elegant & fokussiert',
        'settings.appearance.custom': 'Benutzerdefiniert',
        'settings.appearance.customDesc': 'Eigene Farbpalette',
        'settings.appearance.system': 'System',
        'settings.appearance.systemDesc': 'Dem OS anpassen',
        // API
        'settings.api.secretKeys': 'Geheime Schlüssel',
        'settings.api.manageAuth': 'API-Authentifizierung verwalten',
        'settings.api.createNew': '+ Neuen Schlüssel erstellen',
        'settings.api.noKeys': 'Keine API-Schlüssel gefunden. Erstellen Sie einen, um zu beginnen.',
        'settings.api.copy': 'Kopieren',
        'settings.api.revoke': 'Widerrufen',
        'settings.api.copied': 'In Zwischenablage kopiert',
        'settings.api.created': 'API-Schlüssel erstellt',
        'settings.api.createFailed': 'Schlüssel konnte nicht erstellt werden',
        'settings.api.revoked': 'API-Schlüssel widerrufen',
        'settings.api.revokeFailed': 'Schlüssel konnte nicht widerrufen werden',
        'settings.api.feature': 'API-Zugang',
        'settings.api.featureDesc': 'Integrieren Sie Nalyse in Ihre eigenen Anwendungen und automatisieren Sie Ihre Daten-Workflows mit unserer robusten API.',
        // Notifications
        'settings.notifications.title': 'Benachrichtigungseinstellungen',
        'settings.notifications.desc': 'Konfigurieren Sie, wie und wann Nalyse Sie über verschiedene Plattformmodule benachrichtigt.',
        'settings.notifications.collab.title': 'Zusammenarbeit & Nachrichten',
        'settings.notifications.collab.desc': 'Bleiben Sie über direkte Kommunikation und Teamarbeit informiert.',
        'settings.notifications.collab.dm': 'Direktnachrichten',
        'settings.notifications.collab.dmDesc': 'Benachrichtigung bei neuen privaten Nachrichten.',
        'settings.notifications.collab.mentions': 'Erwähnungen',
        'settings.notifications.collab.mentionsDesc': 'Benachrichtigung bei @-Erwähnung in einem Arbeitsbereich oder Kommentar.',
        'settings.notifications.collab.threadReplies': 'Thread-Antworten',
        'settings.notifications.collab.threadRepliesDesc': 'Benachrichtigung bei Antworten in einem Thread, dem Sie folgen.',
        'settings.notifications.analysis.title': 'Analyse & Intelligenz',
        'settings.notifications.analysis.desc': 'Benachrichtigungen von der Neural Bridge und Decision Engine.',
        'settings.notifications.analysis.complete': 'Analyse abgeschlossen',
        'settings.notifications.analysis.completeDesc': 'Benachrichtigung, wenn große Datenanalyse-Jobs abgeschlossen sind.',
        'settings.notifications.analysis.automl': 'AutoML-Bereitschaft',
        'settings.notifications.analysis.automlDesc': 'Benachrichtigung, wenn ein AutoML-Modell das Training oder die Bereitstellung abgeschlossen hat.',
        'settings.notifications.analysis.anomaly': 'Anomalie-Warnungen',
        'settings.notifications.analysis.anomalyDesc': 'Kritische Warnungen, wenn die Anomalie-Erkennung unerwartete Abweichungen feststellt.',
        'settings.notifications.analysis.scheduled': 'Geplante Berichte',
        'settings.notifications.analysis.scheduledDesc': 'Benachrichtigung, wenn Ihre automatisierten PDF/HTML-Berichte erstellt werden.',
        'settings.notifications.data.title': 'Daten & Infrastruktur',
        'settings.notifications.data.desc': 'Überwachen Sie Ihre Datenpipelines und Integrationen.',
        'settings.notifications.data.syncFailure': 'Synchronisierungsfehler',
        'settings.notifications.data.syncFailureDesc': 'Sofortige Warnungen bei fehlgeschlagener Synchronisierung eines Datenkonnektors.',
        'settings.notifications.data.schemaChange': 'Schema-Änderungen',
        'settings.notifications.data.schemaChangeDesc': 'Benachrichtigung bei Änderungen oder Fehlern in Upstream-Quellschemata.',
        'settings.notifications.data.pipelineSuccess': 'Pipeline erfolgreich',
        'settings.notifications.data.pipelineSuccessDesc': 'Tägliche Zusammenfassung erfolgreich ausgeführter Datenpipelines.',
        'settings.notifications.security.title': 'Sicherheit & Konto',
        'settings.notifications.security.desc': 'Schützen Sie Ihr Konto und bleiben Sie informiert.',
        'settings.notifications.security.newLogins': 'Neue Anmeldungen',
        'settings.notifications.security.newLoginsDesc': 'Warnungen bei Anmeldungen von neuen IP-Adressen oder unbekannten Geräten.',
        'settings.notifications.security.roleChanges': 'Rollen- & Zugriffsänderungen',
        'settings.notifications.security.roleChangesDesc': 'Benachrichtigung bei Aktualisierung Ihrer Berechtigungen oder RBAC-Rollen.',
        'settings.notifications.security.alerts': 'Sicherheitswarnungen',
        'settings.notifications.security.alertsDesc': 'Wichtige Benachrichtigungen über Plattform-Sicherheitsereignisse.',
        'settings.notifications.security.updates': 'Produkt-Updates',
        'settings.notifications.security.updatesDesc': 'Neuigkeiten über neue Nalyse-Funktionen, Verbesserungen und Wartung.',

        // ─── BI Selection ───
        'bi.select.title': 'BI-Intelligenz-Dashboards',
        'bi.select.subtitle': 'Wählen Sie einen analytischen Vektor, um Ihre KI-gestützte Visualisierungsfläche zu starten.',
        'bi.sales.title': 'Umsatz & Erlös',
        'bi.sales.desc': 'Analysieren Sie die finanzielle Leistung, Pipeline-Geschwindigkeit und regionale Umsatzverteilung.',
        'bi.retention.title': 'Kundenbindung',
        'bi.retention.desc': 'Verfolgen Sie Abwanderungsraten, Kohortenüberleben und Nutzerengagement im Zeitverlauf.',
        'bi.supply.title': 'Lieferkette',
        'bi.supply.desc': 'Überwachen Sie Lagerbestände, Lieferantenleistung und Nachbestellungswarnungen.',
        'bi.marketing.title': 'Marketing-ROI',
        'bi.marketing.desc': 'Bewerten Sie Kampagnenausgaben, Konversionstrichter und Kosten pro Akquisition.',
        'bi.product.title': 'Produktanalyse',
        'bi.product.desc': 'Verstehen Sie Feature-Nutzung, Sitzungsdauer und Nutzerpfade.',
        'bi.executive.title': 'Zusammenfassung für Führungskräfte',
        'bi.executive.desc': 'Makroskopische Übersicht über Unternehmensgesundheit, GuV und strategische Ziele.',
        'bi.selectFile': 'Vorhandenen Datensatz auswählen',
        'bi.chooseFile': 'Datei wählen...',
        'bi.launchDashboard': 'Dashboard starten',
        'bi.uploadNew': 'Neuen Datensatz hochladen',
        'bi.expectedColumns': 'Erwartete Spalten:',
        'bi.noFilesYet': 'Noch keine Dateien hochgeladen',
    }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
    const [language, setLanguageState] = useState<Language>(() => {
        return (localStorage.getItem('language') as Language) || 'en';
    });

    const setLanguage = (lang: Language) => {
        setLanguageState(lang);
        localStorage.setItem('language', lang);
    };

    const t = (key: string): string => {
        return translations[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};
